services:
  postgres:
    container_name: kuromi_postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./database/dev/data:/var/lib/postgresql/data
      - ./database/dev/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env