services:
  postgres:
    container_name: kuromi_postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env

  # backend:
  #   container_name: kuromi_backend
  #   image: node:22.13-alpine
  #   ports:
  #     - ${PORT}:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   command: >
  #     sh -c "npm install -g pnpm &&
  #     pnpm config set store-dir /root/.pnpm-store &&
  #     pnpm i &&
  #     pnpm run start:dev
  #     "